INSERT INTO CANDIDATE (EMAIL_ID,NAME) VALUES ('a@gmail.com', 'Abhinav');
INSERT INTO CANDIDATE (EMAIL_ID, NAME) VALUES('b@gmail.com', 'bhuvan');
INSERT INTO OFFER (JOB_TITLE,START_DATE) VALUES('java', '6/11/2020');
INSERT INTO OFFER (JOB_TITLE, START_DATE) VALUES('python', '7/11/2020');
